[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "torch.*",
    "sklearn.*",
    "torch_geometric.*",
    "matplotlib.*",
    "ase.*",
    "dscribe.*",
    "yaml"
]
ignore_missing_imports = true

[tool.ruff]
line-length = 120
