dataset:
  train:
    # path to extxyz files
    src: data/luigi/example-traj-Fe-N2-111.xyz
    # If we want to normalize each target value, i.e. subtract the mean and
    # divide by standard deviation, then those 'target_mean' and 'target_std'
    # statistics for energies and 'grad_target_mean' and 'grad_target_std'
    # statistics for forces need to be specified here for the train split.
    normalize_labels: True
    # These stats are for example-traj-Fe-N2-111.xyz
    target_mean: -34662.8389
    target_std: 0.6950
    grad_target_mean: 0.0
    grad_target_std: 0.5969                                   # True or False
  val:
    # path to extxyz files
    src: data/luigi/example-traj-Fe-N2-111.xyz
  test:
    # path to extxyz files
    src: data/luigi/example-traj-Fe-N2-111.xyz

# Values for logger, such as tagging and name of run
logger:
  tags: ["test"]
  name: "mekrr-gauss-schnet"

kernel:
  k0:
    gaussian
  k0_params:
    median_heuristic: True
  k1:
    linear
  # k1_params
  regressor_params:
    lmbda: 1.0e-3
  representation_params:
    representation_layer: 1
  model_checkpoint_path: checkpoints/s2ef_efwt/all/schnet/schnet_all_large.pt # Path to load model checkpoint

optim:
  # Coefficient to use for the force loss. Currently unused as we only train on energy
  force_loss_coefficient: 0.0

task:
  train: True
  validate: True
  test: True
  predict: ["train", "val", "test"]

runner: "MEKRR"
