dataset:
  train:
    # path to extxyz file
    src: data/luigi/splits/formula=Fe40N2_surface=110_driver=nn-sp_bias=metad_train.xyz
    # If we want to normalize each target value_ i.e. subtract the mean and
    # divide by standard deviation_ then those 'target_mean' and 'target_std'
    # statistics for energies and 'grad_target_mean' and 'grad_target_std'
    # statistics for forces need to be specified here for the train split.
    normalize_labels: True
  val:
    # path to extxyz files
    src: data/luigi/splits/formula=Fe40N2_surface=110_driver=nn-sp_bias=metad_val.xyz
  test:
    # path to extxyz files
    src: data/luigi/splits/formula=Fe40N2_surface=110_driver=nn-sp_bias=metad_test.xyz

# Values for logger, such as tagging and name of run
logger:
  tags: []
  name: "name"

task:
  train: True
  validate: ["train", "val", "test"] # metrics
  predict: ["train", "val", "test"] # prediction

runner: "RUNNER"
