dataset:
  train:
    # path to extxyz files
    src: data/private/1_abinitio-md_Fe45N2_random-true_train.extxyz
    # If we want to normalize each target value_ i.e. subtract the mean and
    # divide by standard deviation_ then those 'target_mean' and 'target_std'
    # statistics for energies and 'grad_target_mean' and 'grad_target_std'
    # statistics for forces need to be specified here for the train split.
    normalize_labels: True
  val:
    # path to extxyz files
    src: data/private/3_active-metad_Fe45N2_random-true_val.extxyz
  test:
    # path to extxyz files
    src: data/private/3_active-metad_Fe45N2_random-true_test.extxyz

model:
  gap_params:
    name: soap
    atom_sigma: 0.5
    l_max: 6
    n_max: 12
    cutoff: 6.0
    cutoff_transition_width: 1.0
    delta: 0.2
    covariance_type: dot_product
    n_sparse: 1000
    zeta: 4
    energy_scale: 1.0
    atom_gaussian_width: 1.0
  other_params:
    default_sigma: [0.001, 0.01, 0.0, 0.0]
    e0_method: average

# Values for logger, such as tagging and name of run
logger:
  tags: []
  name: "gap-soap"

task:
  train: True
  validate: ["train", "test"] # metrics
  predict: ["train", "test"] # prediction

runner: "GAP"
